# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

steps:
- script: echo Hello, world!
  displayName: 'Run a one-line script'

- script: |
    echo Add other tasks to build, test, and deploy your project.
    echo See https://aka.ms/yaml
  displayName: 'Run a multi-line script'
- task: Prisma Cloud IaC Scan@3
  inputs:
    Path: '.'
    prismaCloudService: 'Prisma IAC'
    High: '50'
    Medium: '50'
    Low: '50'
    Operator: 'or'
    Tags: 'name:zs, repo:ado'
- task: Docker@2
  inputs:
    containerRegistry: 'zs-docker'
    command: 'login'
- task: prisma-cloud-compute-scan@3
  inputs:
    scanType: 'images'
    twistlockService: 'zs-PCE'
    artifact: 'zohebsarwar/web1:ubuntu'
- task: Docker@2
  inputs:
    containerRegistry: 'zs-docker'
    repository: 'web1'
    command: 'buildAndPush'
    Dockerfile: '**/ado/docker/DockerFile'
    tags: '$(ado)'